from .paths import IMAGES_DIR, BOARDS_DIR, SOUNDS_DIR, FONTS_DIR, ROOT_DIR
from .ui import (
    WINDOW_WIDTH, WINDOW_HEIGHT,
    BOARD_WIDTH, BOARD_HEIGHT, BOARD_X, BOARD_Y,
    BOARD_ROWS, BOARD_COLS, CELL_WIDTH, CELL_HEIGHT,
    BUTTON_LEVEL_WIDTH, BUTTON_LEVEL_HEIGHT,
    BUTTON_ALGO_WIDTH, BUTTON_ALGO_HEIGHT,
    BUTTON_TOOL, button_xy, button_names
)
from .colors import *

__all__ = [
    # paths
    "ROOT_DIR", "IMAGES_DIR", "BOARDS_DIR", "SOUNDS_DIR", "FONTS_DIR",
    # ui
    "WINDOW_WIDTH", "WINDOW_HEIGHT",
    "BOARD_WIDTH", "BOARD_HEIGHT", "BOARD_X", "BOARD_Y",
    "BOARD_ROWS", "BOARD_COLS", "CELL_WIDTH", "CELL_HEIGHT",
    "BUTTON_LEVEL_WIDTH", "BUTTON_LEVEL_HEIGHT",
    "BUTTON_ALGO_WIDTH", "BUTTON_ALGO_HEIGHT",
    "BUTTON_TOOL", "button_xy", "button_names",
    # colors
    "COLOR_WHITE", "COLOR_BLACK", "COLOR_RED", "COLOR_GREEN", "COLOR_BLUE",
    "COLOR_YELLOW", "COLOR_MAGENTA", "COLOR_CYAN", "COLOR_GRAY",
    "COLOR_BRIGHT_RED", "COLOR_BRIGHT_GREEN", "COLOR_BRIGHT_BLUE",
    "COLOR_BRIGHT_YELLOW", "COLOR_BRIGHT_MAGENTA", "COLOR_BRIGHT_CYAN",
    "COLOR_BRIGHT_WHITE", "COLOR_BRIGHT_BLACK",
]
